### ISSUE TITLE
Question, how can i access to a string inside an array handler by the identifier and index?

### ISSUE THREAD

**Issue by waken22** [trickyloki3/pj59#2]
Hello, i'm struggling to make what the title says.

For example:

```yml
- identifier: energy_drink_research
  handler: array
  array:
    - index: 1
      string: +0% ~ +10% (Base Level)
    - index: 2
      string: +0% ~ +15% (Base Level)
    - index: 3
      string: +0% ~ +20% (Base Level)
```
      
- How could i access to these values in code? (imagine that i want to access to string from index 1)
 
 I can access to a simple constant for example:
 
```c
                        constant = constant_identifier(script->table, y->string);
                        range = script_range_create(script, integer, "%s", constant->tag);
```

This allows me to represent the tag instead of the identifier in some cases, but for arrays i don't know exactly how is done.

More particularly i want to access to strings from an identifier in argument.yml dynamically by their index.
